# Site settings
title: Sign Language Translation Survey Project
email: cassam5@uw.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/SLTSystemsSurvey/" # the subpath of your site, e.g. /blog/
url: "https://cassandra-maz.github.io/SLTSystemsSurvey.github.io/" # the base hostname & protocol for your site

github_username: Cassandra-Maz

# Build settings
markdown: kramdown
